// Offline beat analysis for the background music tracks (www/music/bg_NN.mp3).
//
// For each track: decode to raw mono 44.1kHz PCM via ffmpeg, then run it through
// music-tempo (the "BeatRoot" algorithm) to get a BPM estimate and an array of
// detected beat timestamps (seconds). Results are written to www/music-beats.js
// as a plain `window.MUSIC_BEATS = {...}` global, loaded by index.html alongside
// config.js — the game reads it at runtime to check whether a shot landed on a beat.
//
// Usage: node analyze-beats.js   (run once after adding/changing tracks in www/music/)

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const MusicTempo = require('music-tempo');

const SAMPLE_RATE = 44100; // music-tempo's default params (hopSize 441, timeStep 0.01s) assume 44.1kHz
const MUSIC_DIR = path.join(__dirname, '..', '..', 'www', 'music');
const OUT_FILE = path.join(__dirname, '..', '..', 'www', 'music-beats.js');

function decodeToFloat32(mp3Path) {
  const raw = execFileSync('ffmpeg', [
    '-v', 'error',
    '-i', mp3Path,
    '-ac', '1',
    '-ar', String(SAMPLE_RATE),
    '-f', 'f32le',
    'pipe:1'
  ], { maxBuffer: 1024 * 1024 * 512 });
  // Copy into a fresh, correctly-aligned ArrayBuffer before viewing as Float32Array.
  const ab = raw.buffer.slice(raw.byteOffset, raw.byteOffset + raw.length);
  return new Float32Array(ab);
}

// Default params work for most tracks; quieter/ambient ones can produce too few
// spectral-flux peaks above the default peakThreshold (0.35) and throw "Tempo
// extraction failed" — retry with a lower threshold before giving up.
const PARAM_ATTEMPTS = [{}, { peakThreshold: 0.1 }, { peakThreshold: 0.05, expiryTime: 20 }];

function analyzeTrack(mp3Path) {
  const samples = decodeToFloat32(mp3Path);
  let lastErr;
  for (const params of PARAM_ATTEMPTS) {
    try {
      const mt = new MusicTempo(samples, params);
      return {
        bpm: Math.round(parseFloat(mt.tempo) * 10) / 10,
        beats: mt.beats.map((b) => Math.round(b * 1000) / 1000)
      };
    } catch (e) {
      lastErr = e;
    }
  }
  throw lastErr;
}

function main() {
  const files = fs.readdirSync(MUSIC_DIR)
    .map((f) => /^bg_(\d+)\.mp3$/i.exec(f))
    .filter(Boolean)
    .map((m) => ({ n: parseInt(m[1], 10), file: m[0] }))
    .sort((a, b) => a.n - b.n);

  if (!files.length) {
    console.error('No bg_*.mp3 files found in ' + MUSIC_DIR);
    process.exit(1);
  }

  const results = {};
  for (const { n, file } of files) {
    const full = path.join(MUSIC_DIR, file);
    process.stdout.write('Analyzing ' + file + '... ');
    try {
      const { bpm, beats } = analyzeTrack(full);
      results[n] = { bpm, beats };
      console.log(bpm + ' BPM, ' + beats.length + ' beats');
    } catch (e) {
      console.log('FAILED (' + e + ')');
    }
  }

  const header =
    '// Auto-generated by tools/beat-analysis/analyze-beats.js — do not hand-edit.\n' +
    '// Per-track beat data for www/music/bg_NN.mp3: bpm (estimate) and beats\n' +
    '// (detected beat timestamps, seconds, ascending). Used by MUSIC.isOnBeat()\n' +
    '// in game.js to check whether a shot landed on a beat of the playing track.\n';
  const body = 'window.MUSIC_BEATS = ' + JSON.stringify(results, null, 2) + ';\n';
  fs.writeFileSync(OUT_FILE, header + body);
  console.log('Wrote ' + OUT_FILE);
}

main();
