Listen 192.168.0.10:80

<VirtualHost 192.168.0.10:80>
    ServerName 192.168.0.10
    DocumentRoot "D:/OSPanel/home/vr-shooter/www"
    <Directory "D:/OSPanel/home/vr-shooter/www">
        AllowOverride All
        Options +Indexes +IncludesNoExec +Includes +ExecCGI
        Require all granted
    </Directory>
    php_value error_log "D:/OSPanel/logs/domains/vr_php_error.log"
</VirtualHost>
